# Dockerfile-server-base
FROM python:3.10-slim

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
  rm -f /etc/apt/apt.conf.d/docker-clean && \
  apt-get update && \
  apt-get install -y --no-install-recommends libopus0 ffmpeg

ENV \
  PYTHONUTF8=1 \
  PYTHONIOENCODING=utf-8 \
  PYTHONUNBUFFERED=1

WORKDIR /opt/xiaozhi-esp32-server

RUN --mount=type=bind,src=main/xiaozhi-server/requirements.txt,dst=requirements.txt \
    --mount=type=cache,target=/root/.cache/pip \
  pip install --upgrade pip setuptools wheel && \
  pip install -r requirements.txt --default-timeout=120 --retries 5